"""initial schema

Revision ID: fb496bb08934
Revises: 
Create Date: 2026-06-20 18:11:02.307567

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb496bb08934'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knesset_bill_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('bill_type_desc', sa.String(length=255), nullable=True),
    sa.Column('status_desc', sa.String(length=255), nullable=True),
    sa.Column('knesset_num', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_knesset_bill_id'), ['knesset_bill_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bills_knesset_num'), ['knesset_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knesset_person_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('current_party', sa.String(length=255), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_politicians_current_party'), ['current_party'], unique=False)
        batch_op.create_index(batch_op.f('ix_politicians_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_politicians_knesset_person_id'), ['knesset_person_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_politicians_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('vote_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knesset_vote_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('vote_date', sa.Date(), nullable=True),
    sa.Column('knesset_num', sa.Integer(), nullable=True),
    sa.Column('session_num', sa.Integer(), nullable=True),
    sa.Column('result', sa.Enum('PASSED', 'FAILED', 'UNKNOWN', name='voteresult', native_enum=False, length=32), nullable=False),
    sa.Column('total_for', sa.Integer(), nullable=True),
    sa.Column('total_against', sa.Integer(), nullable=True),
    sa.Column('total_abstain', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vote_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vote_events_knesset_num'), ['knesset_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_events_knesset_vote_id'), ['knesset_vote_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_vote_events_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vote_events_vote_date'), ['vote_date'], unique=False)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('action_type', sa.Enum('ACHIEVEMENT', 'BILL_SPONSORED', 'BILL_PASSED', 'POLICY', 'APPOINTMENT', 'OTHER', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('source_url IS NOT NULL', name='ck_action_requires_source'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actions_action_date'), ['action_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actions_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('bill_sponsorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('is_initiator', sa.Boolean(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'bill_id', name='uq_sponsorship_politician_bill')
    )
    with op.batch_alter_table('bill_sponsorships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_sponsorships_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_sponsorships_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_sponsorships_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('position_desc', sa.String(length=512), nullable=True),
    sa.Column('knesset_num', sa.Integer(), nullable=True),
    sa.Column('government_num', sa.Integer(), nullable=True),
    sa.Column('ministry_name', sa.String(length=512), nullable=True),
    sa.Column('faction_name', sa.String(length=512), nullable=True),
    sa.Column('committee_name', sa.String(length=512), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_knesset_num'), ['knesset_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_start_date'), ['start_date'], unique=False)

    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('topic', sa.String(length=512), nullable=True),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('statement_type', sa.Enum('SPEECH', 'INTERVIEW', 'SOCIAL_MEDIA', 'PRESS_RELEASE', 'PLENUM', 'OTHER', name='statementtype', native_enum=False, length=32), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'SUPPORTED', 'CONTRADICTED', 'NEEDS_REVIEW', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('source_url IS NOT NULL', name='ck_statement_requires_source'),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statements_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_statement_date'), ['statement_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_statements_topic'), ['topic'], unique=False)

    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('vote_event_id', sa.Integer(), nullable=False),
    sa.Column('stance', sa.Enum('FOR', 'AGAINST', 'ABSTAIN', 'ABSENT', 'NA', name='votestance', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vote_event_id'], ['vote_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'vote_event_id', name='uq_vote_politician_event')
    )
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_votes_politician_id'), ['politician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_source_record_id'), ['source_record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_votes_vote_event_id'), ['vote_event_id'], unique=False)

    op.create_table('contradictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('evidence_kind', sa.String(length=32), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('statement_url', sa.String(length=1024), nullable=True),
    sa.Column('evidence_url', sa.String(length=1024), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NEEDS_REVIEW', 'CONFIRMED', 'DISMISSED', name='contradictionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('detector_version', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('human_verdict', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contradictions_statement_id'), ['statement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contradictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contradictions_statement_id'))

    op.drop_table('contradictions')
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_votes_vote_event_id'))
        batch_op.drop_index(batch_op.f('ix_votes_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_votes_politician_id'))

    op.drop_table('votes')
    with op.batch_alter_table('statements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statements_topic'))
        batch_op.drop_index(batch_op.f('ix_statements_statement_date'))
        batch_op.drop_index(batch_op.f('ix_statements_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_statements_politician_id'))

    op.drop_table('statements')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_start_date'))
        batch_op.drop_index(batch_op.f('ix_roles_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_roles_politician_id'))
        batch_op.drop_index(batch_op.f('ix_roles_knesset_num'))

    op.drop_table('roles')
    with op.batch_alter_table('bill_sponsorships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_sponsorships_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_bill_sponsorships_politician_id'))
        batch_op.drop_index(batch_op.f('ix_bill_sponsorships_bill_id'))

    op.drop_table('bill_sponsorships')
    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actions_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_actions_politician_id'))
        batch_op.drop_index(batch_op.f('ix_actions_action_date'))

    op.drop_table('actions')
    with op.batch_alter_table('vote_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vote_events_vote_date'))
        batch_op.drop_index(batch_op.f('ix_vote_events_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_vote_events_knesset_vote_id'))
        batch_op.drop_index(batch_op.f('ix_vote_events_knesset_num'))

    op.drop_table('vote_events')
    with op.batch_alter_table('politicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_politicians_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_politicians_knesset_person_id'))
        batch_op.drop_index(batch_op.f('ix_politicians_full_name'))
        batch_op.drop_index(batch_op.f('ix_politicians_current_party'))

    op.drop_table('politicians')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_bills_knesset_num'))
        batch_op.drop_index(batch_op.f('ix_bills_knesset_bill_id'))

    op.drop_table('bills')
    # ### end Alembic commands ###
