"""add official_statistics and statistic_verdicts

Revision ID: f24d1de96d52
Revises: fb496bb08934
Create Date: 2026-06-26 18:03:52.012868

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24d1de96d52'
down_revision: Union[str, None] = 'fb496bb08934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(length=128), nullable=False),
    sa.Column('dimension_type', sa.String(length=32), nullable=False),
    sa.Column('dimension_value', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source_type', sa.Enum('KNESSET_ODATA', 'KNESSET_VOTES', 'OPEN_KNESSET', 'BUDGET_KEY', 'STATE_COMPTROLLER', 'CBS', 'IDF_SPOKESPERSON', 'COURT', 'CORPORATIONS_AUTHORITY', 'MANUAL', name='sourcetype', native_enum=False, length=32), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('source_url IS NOT NULL', name='ck_official_statistic_requires_source'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('official_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_official_statistics_dimension_type'), ['dimension_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_statistics_dimension_value'), ['dimension_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_statistics_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_official_statistics_source_record_id'), ['source_record_id'], unique=False)

    op.create_table('statistic_verdicts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('official_statistic_id', sa.Integer(), nullable=True),
    sa.Column('statistic_ids', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.Enum('CONSISTENT', 'INCONSISTENT', 'UNVERIFIABLE', name='verdictoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('numeric_gap', sa.Float(), nullable=True),
    sa.Column('statement_url', sa.String(length=1024), nullable=True),
    sa.Column('statistic_url', sa.String(length=1024), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('adjudicator_version', sa.String(length=64), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('auto_published', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verdictreviewstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['official_statistic_id'], ['official_statistics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('statistic_verdicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_statistic_verdicts_statement_id'), ['statement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statistic_verdicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_statistic_verdicts_statement_id'))

    op.drop_table('statistic_verdicts')
    with op.batch_alter_table('official_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_official_statistics_source_record_id'))
        batch_op.drop_index(batch_op.f('ix_official_statistics_metric'))
        batch_op.drop_index(batch_op.f('ix_official_statistics_dimension_value'))
        batch_op.drop_index(batch_op.f('ix_official_statistics_dimension_type'))

    op.drop_table('official_statistics')
    # ### end Alembic commands ###
